name: Deploy EnlaceCRM Desarrollo formulario en servidor windows automatico

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio en la ruta destino
        shell: powershell
        run: |
          $destino = "C:\EnlaceCRM\EnlaceCRM_desarrollo\EnlaceCRMFormulario"
          if (Test-Path $destino) {
            Set-Location $destino
            git fetch --all
            git reset --hard origin/develop
          }

      - name: Instalar dependencias
        shell: powershell
        run: |
          Set-Location "C:\EnlaceCRM\EnlaceCRM_desarrollo\EnlaceCRMFormulario"
          npm install

      - name: Compilar Vue app
        shell: powershell
        run: |
          Set-Location "C:\EnlaceCRM\EnlaceCRM_desarrollo\EnlaceCRMFormulario"
          npm run build

      - name: Reiniciar Nginx
        shell: powershell
        run: |
          Set-Location "C:\Nginx\nginx-1.28.0"
          .\nginx.exe -s reload