name: Deploy EnlaceCRM formulario en servidor IIS automatico 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Vue app
        run: npm run build

      - name: Copiar archivos compilados a ruta de IIS
        shell: powershell
        run: |
          $destino = "C:\Users\sap-basis\Desktop\RegistroEnlaceCRM\dist"
          if (Test-Path $destino) {
            Remove-Item -Recurse -Force "$destino\*"
          } else {
            New-Item -ItemType Directory -Path $destino | Out-Null
          }
          Copy-Item -Path "dist\*" -Destination $destino -Recurse

      - name: Reiniciar IIS
        shell: powershell
        run: |
          iisreset /restart
